version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - python -m pip install -v . --no-build-isolation

conda:
  environment: doc/environment.yml

sphinx:
  fail_on_warning: true

formats: []
