package:
  name: fastscapelib-python
  version: "0.1"

source:
  path: ../..
  # git_url: https://github.com/fastscape-lem/fastscapelib.git
  # git_rev: master

build:
  number: 0
  script: cd python; python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - xtensor
    - xtensor-python
    - python
    - setuptools
    - pybind11
    - numpy
  host:
    - python
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - fastscapelib

about:
  home: https://github.com/fastscape-lem/fastscapelib
  license: GPLv3
  summary: 'Python bindings for the fastscapelib C++ library'
  description: |
    Library implementing efficient algorithms for processing
    topographic data and landscape evolution modeling
