package:
  name: fastscapelib
  version: "0.1"

source:
  path: ../..
  # git_url: https://github.com/fastscape-lem/fastscapelib.git
  # git_rev: master

build:
  number: 0
  skip: true   # [win and vc<14]

outputs:
  - name: fastscapelib
    script: install_cpp_headers.sh   # [unix]
    script: install_cpp_headers.bat  # [win]
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - xtensor >=0.16.0
      run:
        - xtensor >=0.16.0
    test:
      commands:
        - test -d ${PREFIX}/include/fastscapelib  # [unix]
        - test -f ${PREFIX}/include/fastscapelib/fastscapelib.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfig.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/fastscapelib/fastscapelibConfigVersion.cmake  # [unix]
        # TODO: replace with %PREFIX%\Library with %LIBRARY_PREFIX%
        - if exist %PREFIX%\Library\include\fastscapelib\fastscapelib.hpp (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\Library\lib\cmake\fastscapelibConfig.cmake (exit 0) else (exit 1)  # [win]
        - if exist %PREFIX%\Library\lib\cmake\fastscapelibConfigVersion.cmake (exit 0) else (exit 1)  # [win]
  - name: fastscapelib-python
    script: install_python.sh   # [unix]
    script: install_python.bat  # [win]
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - xtensor
        - xtensor-python
        - python {{ python }}
        - setuptools
        - pybind11
        - numpy
      host:
        - python
        - numpy
      run:
        - python
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - fastscapelib

about:
  home: https://github.com/fastscape-lem/fastscapelib
  license: GPLv3
  license_file: LICENSE
  summary: 'Library for topographic analysis and modeling'
  description: |
    Fastscapelib is a C++ library that implements efficient algorithms
    for processing topographic data and landscape evolution
    modeling. It also has Python bindings.
