jobs:
  - job: 'MacOS'
    strategy:
      matrix:
        mojave_10_14:
          image_name: 'macOS-10.14'
        catalina_10_15:
          image_name: 'macOS-10.15'
    pool:
      vmImage: $(image_name)
    variables:
        CC: clang
        CXX: clang++
    timeoutInMinutes: 360
    steps:
      - script: |
          echo "Removing homebrew for Azure to avoid conflicts with conda"
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          sudo ~/uninstall_homebrew -f -q
        displayName: Remove homebrew
      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          sudo chown -R $USER $CONDA
        displayName: Add conda to PATH
      - template: unix-build.yml
