jobs:
  - job: 'macos_py'
    strategy:
      matrix:
        python_38:
          python_version: '3.8'
    pool:
      vmImage: 'macOS-10.15'
    variables:
        CC: clang
        CXX: clang++
    timeoutInMinutes: 360
    steps:
      - script: |
          echo "Removing homebrew for Azure to avoid conflicts with conda"
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          ~/uninstall_homebrew -f -q
        displayName: Remove homebrew
      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          sudo chown -R $USER $CONDA
        displayName: Add conda to PATH
      - template: unix-build-python.yml
