on:
  # trigger action from GitHub GUI (testing, no publish)
  workflow_dispatch:
  release:
    types:
      - published

name: Python wheels

jobs:
  make_sdist:
    name: Make Python SDist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - name: Upload SDist
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheel (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21
        env:
          # skip PyPy and muslinux (for now)
          CIBW_SKIP: "pp* *musllinux*"
          # skip 32-bits platforms on linux and windows
          CIBW_ARCHS_LINUX: "auto64"
          CIBW_ARCHS_WINDOWS: "auto64"
          # macos: opt-in cross-compile on arm64
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_TEST_SKIP: "*_arm64 *_universal2:arm64"

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  upload_all:
    needs: [build_wheels, make_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Get dist files
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
